name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 */5 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: zhashut/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: f52214715f6948c19aa9ebcc130616c8
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
